<script lang="ts">
	import DataTable from "$lib/components/ui/data-table.svelte";
	import players from "$lib/data/inazuma-eleven-vr/players.json"; // generated by your scraper

	// Element → Tailwind color
	const elementColor: Record<string, string> = {
		Mountain: "bg-yellow-800/75",
		Fire: "bg-red-800/75",
		Forest: "bg-green-800/75",
		Wind: "bg-sky-800/75"
	};

	const positionColor: Record<string, string> = {
		GK: "bg-yellow-900",
		DF: "bg-blue-900",
		MF: "bg-green-900",
		FW: "bg-red-900",
	};

	// DataTable columns
	const columns = [
		{
			key: "player",
			label: "Player",
			width: "275px",
			render: (p) => `
				<div class="flex items-center gap-3">
					<div class="w-14 h-14 ${elementColor[p.Element] ?? "bg-neutral-700"}">
						<img src="${p.Image}" alt="${p.Name}" class="w-full h-full object-cover"/>
					</div>
					<div>
						<div>${p.Name}</div>
						<div class="text-xs inline-block px-1 border ${positionColor[p.Position] ?? "bg-neutral-700"}">
							${p.Position}
						</div>
					</div>
				</div>
			`,
			searchValue: (p) => `${p.Name} ${p.Nickname} ${p.Position}`
		},
		{ key: "Kick", label: "Kick" },
		{ key: "Control", label: "Control" },
		{ key: "Technique", label: "Technique" },
		{ key: "Pressure", label: "Pression" },
		{ key: "Physical", label: "Physical" },
		{ key: "Agility", label: "Agility" },
		{ key: "Intelligence", label: "Intelligence" },
		{
			key: "Total",
			label: "Total",
			render: (p) => `<span class="font-bold">${p.Total}</span>`
		}
	];

	const rows = players.filter(p => !p.Name.includes("?"));

</script>

<DataTable {columns} {rows} pageSize={50} />
